name: DeployTest

# Deploy on every push to the repository on master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Builds tesc.ucsd.edu for deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Build tesc.ucsd.edu
        run: npm install && CI=false npm run build
        shell: bash
      # - name: Test ssh
      #   env:
      #     DEPLOY_KEY: ${{ secrets.NEW_SERVER_KEY }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
      #   run: |
      #     mkdir ~/.ssh
      #     echo "${{ secrets.NEW_SERVER_KEY }}" > ~/.ssh/gh-actions-key
      #     chmod 600 ~/.ssh/gh-actions-key
      #     ssh ${REMOTE_USER}@${REMOTE_HOST} -i ~/.ssh/gh-actions-key -o StrictHostKeyChecking=no
      - name: Move files with rsync
        # mkdir .ssh
        # touch .ssh/gh-actions-key
        # ls -a .ssh
        run: |
          echo "HELLO IM ABOUT TO ls 1"
          ls -a -l
          mkdir $HOME/.ssh
          touch $HOME/.ssh/gh-actions-key
          echo "HELLO IM ABOUT TO ls only ssh"
          ls -a $HOME/.ssh
          echo "creating super secret key file"
      - name: Creating SSH Key
        env:
          DEPLOY_KEY: ${{ secrets.NEW_SERVER_KEY }}
        run: 'echo "$DEPLOY_KEY" > $HOME/.ssh/gh-actions-key'
      - name: Continue Deploy
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          echo "doing chmod stuff"
          wc -l ~/.ssh/gh-actions-key
          sudo chmod 700 $HOME/.ssh
          sudo chmod 600 $HOME/.ssh/gh-actions-key
          echo "HELLO IM ABOUT TO ls 3"
          echo "HOME $HOME"
          echo "pwd $(pwd)"
      - name: Run expect...send script
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get install expect
          sudo chmod +x ./scripts/script.sh
          ./scripts/script.sh
        # rsync -avzr --delete -e "ssh -i $HOME/.ssh/gh-actions-key -o StrictHostKeyChecking=no" "build/" ${REMOTE_USER}@${REMOTE_HOST}:~/htdocs
        # rsync -avzr --delete -e "ssh -i $(pwd)/.ssh/gh-actions-key -o StrictHostKeyChecking=no" "build/" ${REMOTE_USER}@${REMOTE_HOST}:~/htdocs
        # chmod +x ./scripts/script.sh
        # ./scripts/script.sh
        # spawn rsync -avzr --delete -e "ssh -i ~/.ssh/gh-actions-key -o StrictHostKeyChecking=no" "build/" ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}
