name: Deploy

# Deploy on every push to the repository on master
# Or whenever we manually run it
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Builds tesc.ucsd.edu for deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Set up .env
        env: 
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_READ_ONLY_API_KEY }}
        run: |
          echo "REACT_APP_AIRTABLE_KEY=$AIRTABLE_KEY" > .env
      - name: Build tesc.ucsd.edu
        run: npm install && CI=false npm run build
        shell: bash
      - name: Move files with rsync
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get install expect
          sudo chmod +x ./scripts/ping-test-website
          sudo chmod +x ./scripts/rsync-website.except
          ./scripts/ping-test-website
          ./scripts/rsync-website.except $SSH_PASSWORD
