name: DeployTest

# Deploy on every push to the repository on master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Builds tesc.ucsd.edu for deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Build tesc.ucsd.edu
        run: npm install && CI=false npm run build
        shell: bash
      # - name: Test ssh
      #   env:
      #     DEPLOY_KEY: ${{ secrets.NEW_SERVER_KEY }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
      #   run: |
      #     mkdir ~/.ssh
      #     echo "${{ secrets.NEW_SERVER_KEY }}" > ~/.ssh/gh-actions-key
      #     chmod 600 ~/.ssh/gh-actions-key
      #     ssh ${REMOTE_USER}@${REMOTE_HOST} -i ~/.ssh/gh-actions-key -o StrictHostKeyChecking=no
      - name: Move files with rsync
        env:
          DEPLOY_KEY: ${{ secrets.NEW_SERVER_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        # sudo apt-get install expect
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/gh-actions-key
          echo ${{ secrets.NEW_SERVER_KEY }} > ~/.ssh/gh-actions-key
          chmod 700 ~/.ssh/gh-actions-key
          echo HELLO IM ABOUT TO ls
          ls -a -l
          rsync -avzr --delete -e "ssh -i ~/.ssh/gh-actions-key -o StrictHostKeyChecking=no" "build/" ${REMOTE_USER}@${REMOTE_HOST}:${{ secrets.REMOTE_DIR }}
        # chmod +x ./scripts/script.sh
        # ./scripts/script.sh
        # spawn rsync -avzr --delete -e "ssh -i ~/.ssh/gh-actions-key -o StrictHostKeyChecking=no" "build/" ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}